# Starter pipeline
trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
- group: tokens

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - script: npm install -g gatsby-cli
    displayName: 'Install gatsby'

  - script: gatsby --version
    displayName: 'Verify gatsby installation'

  - script: npm install
    displayName: 'npm install'

  - script: gatsby build
    displayName: 'Building gatsby'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      app_build_command: 'gatsby build'
      output_location: 'public'
      azure_static_web_apps_api_token: $(static-web-app-deployment-token)