trigger:
  branches:
    include:
      - master
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: tokens

stages:
  - stage: DeployToQA
    jobs:
      - job: 
        steps:
            - task: NodeTool@0
              inputs:
                versionSpec: "14.x"
            - script: npm install
              displayName: "npm install"

  - stage: DeployToPROD
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - job: 
        steps:
            - task: NodeTool@0
              inputs:
                versionSpec: "14.x"
            - script: npm install
              displayName: "npm install"
